// ─── Deal Metadata Configuration ─────────────────────────────────────────────
// Central config for all controlled-vocabulary option lists used in deal forms,
// filters, and analytics. Extend these lists rather than hardcoding in components.

// ─── Deal Source ──────────────────────────────────────────────────────────────

export const DEAL_SOURCE_CATEGORIES = [
  "Marketplace Listing",
  "Broker Outreach",
  "Direct Seller",
  "Referral / Network",
  "Cold Outreach",
  "Franchise Resale",
  "Other",
] as const;

export type DealSourceCategory = (typeof DEAL_SOURCE_CATEGORIES)[number];

// Common detail values per category — used as suggestions, not enforced.
export const DEAL_SOURCE_DETAIL_SUGGESTIONS: Record<DealSourceCategory, string[]> = {
  "Marketplace Listing": [
    "BizBuySell",
    "BizQuest",
    "LoopNet",
    "Axial",
    "Flippa",
    "Empire Flippers",
    "Quiet Light",
    "Website Closers",
    "MicroAcquire",
    "Other marketplace",
  ],
  "Broker Outreach": [
    "Broker email",
    "Broker phone call",
    "Broker newsletter",
    "Broker referral",
  ],
  "Direct Seller": [
    "Seller email",
    "Seller phone call",
    "LinkedIn",
    "In-person meeting",
  ],
  "Referral / Network": [
    "Peer referral",
    "Advisor referral",
    "Attorney referral",
    "Accountant referral",
    "Investor network",
    "ETA community",
  ],
  "Cold Outreach": [
    "Direct mail",
    "Cold email",
    "Cold call",
    "Door-to-door",
  ],
  "Franchise Resale": [
    "Franchisor resale program",
    "FranConnect",
    "Franchise broker",
  ],
  Other: [],
};

// ─── Industry ─────────────────────────────────────────────────────────────────

export const INDUSTRY_CATEGORIES = [
  "Automotive",
  "Beauty & Personal Care",
  "Cleaning & Facility Services",
  "Construction",
  "Education & Care",
  "Fitness & Wellness",
  "Food & Beverage",
  "Healthcare",
  "Home Services",
  "Hospitality",
  "Logistics & Transportation",
  "Manufacturing",
  "Pet Services",
  "Professional Services",
  "Retail",
  "Senior Care",
  "Technology",
  "Other",
] as const;

export type IndustryCategory = (typeof INDUSTRY_CATEGORIES)[number];

export const INDUSTRIES_BY_CATEGORY: Record<IndustryCategory, string[]> = {
  Automotive: ["Auto Repair", "Auto Body", "Car Wash", "Tire Shop", "Auto Detailing", "Other Automotive"],
  "Beauty & Personal Care": ["Salon", "Barbershop", "Spa", "Nail Salon", "Lash Studio", "Tattoo Studio", "Other Beauty"],
  "Cleaning & Facility Services": [
    "Commercial Cleaning",
    "Janitorial",
    "Residential Cleaning",
    "Window Cleaning",
    "Pressure Washing",
    "Other Cleaning",
  ],
  Construction: [
    "General Contractor",
    "Specialty Contractor",
    "Remodeling",
    "Commercial Construction",
    "Demolition",
    "Other Construction",
  ],
  "Education & Care": [
    "Childcare",
    "Preschool",
    "Tutoring Center",
    "After School Program",
    "Test Prep",
    "Language School",
    "Other Education",
  ],
  "Fitness & Wellness": [
    "Gym",
    "Yoga Studio",
    "Med Spa",
    "Massage Therapy",
    "Personal Training",
    "Pilates Studio",
    "Other Fitness",
  ],
  "Food & Beverage": [
    "Restaurant",
    "Cafe",
    "Bakery",
    "Catering",
    "Bar / Brewery",
    "Food Truck",
    "Pizza Shop",
    "Other Food & Beverage",
  ],
  Healthcare: [
    "Medical Practice",
    "Dental Practice",
    "Physical Therapy",
    "Home Health",
    "Chiropractic",
    "Optometry",
    "Urgent Care",
    "Other Healthcare",
  ],
  "Home Services": [
    "HVAC",
    "Plumbing",
    "Electrical",
    "Landscaping",
    "Pool Service",
    "Roofing",
    "Painting",
    "Flooring",
    "Window Treatment",
    "Pest Control",
    "Irrigation",
    "Other Home Services",
  ],
  Hospitality: ["Hotel / Motel", "Bed & Breakfast", "Vacation Rental", "Event Venue", "Other Hospitality"],
  "Logistics & Transportation": [
    "Logistics / Trucking",
    "Last Mile Delivery",
    "Freight Brokerage",
    "Moving Company",
    "Courier Service",
    "Other Logistics",
  ],
  Manufacturing: [
    "Light Manufacturing",
    "Contract Manufacturing",
    "Food Manufacturing",
    "Metal Fabrication",
    "Printing",
    "Other Manufacturing",
  ],
  "Pet Services": ["Pet Grooming", "Pet Boarding", "Veterinary Clinic", "Dog Training", "Pet Daycare", "Other Pet Services"],
  "Professional Services": [
    "Staffing Agency",
    "Marketing Agency",
    "Accounting Firm",
    "IT Services",
    "Insurance Agency",
    "Law Firm",
    "Engineering Firm",
    "Other Professional Services",
  ],
  Retail: [
    "Convenience Store",
    "Specialty Retail",
    "E-commerce",
    "Liquor Store",
    "Pharmacy",
    "Sporting Goods",
    "Furniture Store",
    "Other Retail",
  ],
  "Senior Care": ["Senior Care", "Assisted Living", "Adult Day Care", "Memory Care", "Other Senior Care"],
  Technology: [
    "SaaS",
    "Managed IT Services",
    "Software Development",
    "IT Consulting",
    "Cybersecurity",
    "Other Technology",
  ],
  Other: ["Other"],
};

// ─── US States ────────────────────────────────────────────────────────────────

export interface USState {
  abbr: string;
  name: string;
}

export const US_STATES: USState[] = [
  { abbr: "AL", name: "Alabama" },
  { abbr: "AK", name: "Alaska" },
  { abbr: "AZ", name: "Arizona" },
  { abbr: "AR", name: "Arkansas" },
  { abbr: "CA", name: "California" },
  { abbr: "CO", name: "Colorado" },
  { abbr: "CT", name: "Connecticut" },
  { abbr: "DE", name: "Delaware" },
  { abbr: "FL", name: "Florida" },
  { abbr: "GA", name: "Georgia" },
  { abbr: "HI", name: "Hawaii" },
  { abbr: "ID", name: "Idaho" },
  { abbr: "IL", name: "Illinois" },
  { abbr: "IN", name: "Indiana" },
  { abbr: "IA", name: "Iowa" },
  { abbr: "KS", name: "Kansas" },
  { abbr: "KY", name: "Kentucky" },
  { abbr: "LA", name: "Louisiana" },
  { abbr: "ME", name: "Maine" },
  { abbr: "MD", name: "Maryland" },
  { abbr: "MA", name: "Massachusetts" },
  { abbr: "MI", name: "Michigan" },
  { abbr: "MN", name: "Minnesota" },
  { abbr: "MS", name: "Mississippi" },
  { abbr: "MO", name: "Missouri" },
  { abbr: "MT", name: "Montana" },
  { abbr: "NE", name: "Nebraska" },
  { abbr: "NV", name: "Nevada" },
  { abbr: "NH", name: "New Hampshire" },
  { abbr: "NJ", name: "New Jersey" },
  { abbr: "NM", name: "New Mexico" },
  { abbr: "NY", name: "New York" },
  { abbr: "NC", name: "North Carolina" },
  { abbr: "ND", name: "North Dakota" },
  { abbr: "OH", name: "Ohio" },
  { abbr: "OK", name: "Oklahoma" },
  { abbr: "OR", name: "Oregon" },
  { abbr: "PA", name: "Pennsylvania" },
  { abbr: "RI", name: "Rhode Island" },
  { abbr: "SC", name: "South Carolina" },
  { abbr: "SD", name: "South Dakota" },
  { abbr: "TN", name: "Tennessee" },
  { abbr: "TX", name: "Texas" },
  { abbr: "UT", name: "Utah" },
  { abbr: "VT", name: "Vermont" },
  { abbr: "VA", name: "Virginia" },
  { abbr: "WA", name: "Washington" },
  { abbr: "WV", name: "West Virginia" },
  { abbr: "WI", name: "Wisconsin" },
  { abbr: "WY", name: "Wyoming" },
  { abbr: "DC", name: "Washington, D.C." },
];

// ─── US Counties by State ─────────────────────────────────────────────────────

export const COUNTIES_BY_STATE: Record<string, string[]> = {
  AL: ["Baldwin", "Jefferson", "Madison", "Mobile", "Montgomery", "Shelby", "Tuscaloosa"],
  AK: ["Anchorage", "Fairbanks North Star", "Matanuska-Susitna"],
  AZ: ["Cochise", "Maricopa", "Mohave", "Pima", "Pinal", "Yavapai", "Yuma"],
  AR: ["Benton", "Craighead", "Faulkner", "Pulaski", "Saline", "Sebastian", "Washington"],
  CA: ["Alameda","Contra Costa","Fresno","Kern","Los Angeles","Marin","Monterey","Orange","Placer","Riverside","Sacramento","San Bernardino","San Diego","San Francisco","San Joaquin","San Mateo","Santa Barbara","Santa Clara","Santa Cruz","Shasta","Solano","Sonoma","Stanislaus","Tulare","Ventura"],
  CO: ["Adams","Arapahoe","Boulder","Denver","Douglas","El Paso","Jefferson","Larimer","Weld"],
  CT: ["Fairfield","Hartford","Litchfield","Middlesex","New Haven","New London","Tolland","Windham"],
  DE: ["Kent","New Castle","Sussex"],
  FL: ["Alachua","Bay","Brevard","Broward","Charlotte","Citrus","Clay","Collier","Duval","Escambia","Hillsborough","Indian River","Lake","Lee","Leon","Manatee","Marion","Martin","Miami-Dade","Nassau","Okaloosa","Orange","Osceola","Palm Beach","Pasco","Pinellas","Polk","Putnam","Sarasota","Seminole","St. Johns","St. Lucie","Sumter","Volusia"],
  GA: ["Bartow","Carroll","Cherokee","Clayton","Cobb","Columbia","DeKalb","Forsyth","Fulton","Gwinnett","Hall","Henry","Houston","Muscogee","Newton","Paulding","Richmond","Rockdale","Spalding","Whitfield"],
  HI: ["Hawaii","Honolulu","Kauai","Maui"],
  ID: ["Ada","Bannock","Bonneville","Canyon","Kootenai","Twin Falls"],
  IL: ["Champaign","Cook","DuPage","Kane","Kankakee","Kendall","Lake","McHenry","Peoria","Rock Island","Sangamon","St. Clair","Will","Winnebago"],
  IN: ["Allen","Bartholomew","Elkhart","Hamilton","Hancock","Hendricks","Johnson","Lake","Madison","Marion","Monroe","St. Joseph","Tippecanoe","Vanderburgh","Vigo"],
  IA: ["Black Hawk","Dallas","Dubuque","Johnson","Linn","Polk","Pottawattamie","Scott","Story","Woodbury"],
  KS: ["Douglas","Johnson","Leavenworth","Sedgwick","Shawnee","Wyandotte"],
  KY: ["Boone","Campbell","Christian","Daviess","Fayette","Jefferson","Kenton","Madison","Warren"],
  LA: ["Ascension","Bossier","Caddo","Calcasieu","East Baton Rouge","Jefferson","Lafayette","Orleans","Ouachita","St. Tammany"],
  ME: ["Androscoggin","Cumberland","Kennebec","Penobscot","York"],
  MD: ["Anne Arundel","Baltimore City","Baltimore County","Charles","Frederick","Harford","Howard","Montgomery","Prince George's"],
  MA: ["Barnstable","Bristol","Essex","Hampden","Hampshire","Middlesex","Norfolk","Plymouth","Suffolk","Worcester"],
  MI: ["Genesee","Ingham","Jackson","Kalamazoo","Kent","Macomb","Monroe","Muskegon","Oakland","Ottawa","Saginaw","Washtenaw","Wayne"],
  MN: ["Anoka","Carver","Dakota","Hennepin","Olmsted","Ramsey","Scott","St. Louis","Washington"],
  MS: ["DeSoto","Forrest","Harrison","Hinds","Jackson","Lamar","Madison","Rankin"],
  MO: ["Boone","Buchanan","Cape Girardeau","Clay","Greene","Jackson","Jefferson","Platte","St. Charles","St. Louis City","St. Louis County"],
  MT: ["Cascade","Flathead","Gallatin","Lewis and Clark","Missoula","Yellowstone"],
  NE: ["Douglas","Lancaster","Sarpy"],
  NV: ["Clark","Elko","Lyon","Washoe"],
  NH: ["Hillsborough","Merrimack","Rockingham","Strafford"],
  NJ: ["Atlantic","Bergen","Burlington","Camden","Cape May","Essex","Gloucester","Hudson","Hunterdon","Mercer","Middlesex","Monmouth","Morris","Ocean","Passaic","Somerset","Sussex","Union","Warren"],
  NM: ["Bernalillo","Chaves","Doña Ana","Eddy","Lea","Sandoval","Santa Fe","Valencia"],
  NY: ["Albany","Bronx","Broome","Dutchess","Erie","Kings","Monroe","Nassau","New York","Niagara","Onondaga","Orange","Queens","Richmond","Rockland","Saratoga","Suffolk","Ulster","Westchester"],
  NC: ["Alamance","Buncombe","Cabarrus","Catawba","Cumberland","Durham","Forsyth","Gaston","Guilford","Henderson","Iredell","Johnston","Mecklenburg","New Hanover","Onslow","Orange","Pitt","Randolph","Rowan","Union","Wake"],
  ND: ["Burleigh","Cass","Grand Forks","Ward"],
  OH: ["Butler","Clark","Clermont","Cuyahoga","Delaware","Franklin","Greene","Hamilton","Lake","Licking","Lorain","Lucas","Mahoning","Medina","Montgomery","Portage","Stark","Summit","Trumbull","Warren","Wood"],
  OK: ["Canadian","Cleveland","Comanche","Creek","Muskogee","Oklahoma","Tulsa","Washington"],
  OR: ["Clackamas","Deschutes","Jackson","Lane","Linn","Marion","Multnomah","Washington"],
  PA: ["Allegheny","Berks","Bucks","Butler","Chester","Cumberland","Dauphin","Delaware","Erie","Lancaster","Lebanon","Lehigh","Luzerne","Monroe","Montgomery","Northampton","Philadelphia","Westmoreland","York"],
  RI: ["Bristol","Kent","Newport","Providence","Washington"],
  SC: ["Anderson","Berkeley","Charleston","Greenville","Horry","Lexington","Richland","Spartanburg","York"],
  SD: ["Minnehaha","Pennington"],
  TN: ["Blount","Bradley","Davidson","Hamilton","Knox","Madison","Maury","Montgomery","Rutherford","Shelby","Sullivan","Sumner","Washington","Williamson","Wilson"],
  TX: ["Bell","Bexar","Brazoria","Brazos","Cameron","Collin","Comal","Dallas","Denton","El Paso","Fort Bend","Galveston","Harris","Hays","Hidalgo","Jefferson","Johnson","Lubbock","McLennan","Montgomery","Nueces","Parker","Potter","Randall","Smith","Tarrant","Taylor","Travis","Webb","Williamson"],
  UT: ["Cache","Davis","Salt Lake","Utah","Washington","Weber"],
  VT: ["Addison","Chittenden","Rutland","Washington","Windham","Windsor"],
  VA: ["Alexandria City","Arlington","Chesterfield","Fairfax","Henrico","Loudoun","Prince William","Richmond City","Roanoke","Virginia Beach City"],
  WA: ["Clark","King","Kitsap","Pierce","Snohomish","Spokane","Thurston","Whatcom","Yakima"],
  WV: ["Berkeley","Cabell","Kanawha","Monongalia","Wood"],
  WI: ["Brown","Dane","Kenosha","La Crosse","Marathon","Milwaukee","Outagamie","Racine","Rock","Sheboygan","Waukesha","Winnebago"],
  WY: ["Campbell","Laramie","Natrona","Sweetwater"],
  DC: ["Washington"],
};

// ─── US Cities by County ──────────────────────────────────────────────────────
// Key format: `${stateAbbr}::${countyName}`

export const CITIES_BY_COUNTY: Record<string, string[]> = {
  // Alabama
  "AL::Jefferson": ["Birmingham","Bessemer","Hoover","Vestavia Hills","Homewood"],
  "AL::Madison": ["Huntsville","Madison","Decatur"],
  "AL::Mobile": ["Mobile","Prichard","Saraland"],
  "AL::Montgomery": ["Montgomery","Prattville"],
  "AL::Baldwin": ["Daphne","Fairhope","Spanish Fort","Gulf Shores"],
  "AL::Shelby": ["Alabaster","Helena","Pelham","Chelsea"],
  "AL::Tuscaloosa": ["Tuscaloosa","Northport"],
  // Arizona
  "AZ::Maricopa": ["Phoenix","Mesa","Chandler","Scottsdale","Glendale","Tempe","Gilbert","Peoria","Surprise","Goodyear","Avondale","Buckeye","Tolleson"],
  "AZ::Pima": ["Tucson","Marana","Oro Valley","Sahuarita","South Tucson"],
  "AZ::Pinal": ["Casa Grande","Apache Junction","Maricopa","Queen Creek","Florence"],
  "AZ::Yavapai": ["Prescott","Prescott Valley","Cottonwood","Sedona"],
  "AZ::Mohave": ["Kingman","Bullhead City","Lake Havasu City","Fort Mohave"],
  "AZ::Cochise": ["Sierra Vista","Douglas","Bisbee","Benson"],
  "AZ::Yuma": ["Yuma","San Luis","Somerton"],
  // Arkansas
  "AR::Pulaski": ["Little Rock","North Little Rock","Maumelle","Jacksonville"],
  "AR::Benton": ["Bentonville","Rogers","Fayetteville","Springdale","Siloam Springs"],
  "AR::Washington": ["Fayetteville","Springdale","Farmington"],
  "AR::Faulkner": ["Conway","Greenbrier","Vilonia"],
  "AR::Saline": ["Benton","Bryant","Bauxite"],
  "AR::Sebastian": ["Fort Smith","Greenwood","Van Buren"],
  "AR::Craighead": ["Jonesboro","Brookland"],
  // California
  "CA::Los Angeles": ["Los Angeles","Long Beach","Glendale","Pasadena","Torrance","Burbank","Inglewood","Santa Monica","Hawthorne","Downey","El Monte","Pomona","Compton","West Covina","Carson","Norwalk","Inglewood","Whittier"],
  "CA::San Diego": ["San Diego","Chula Vista","Escondido","El Cajon","Oceanside","Carlsbad","Vista","San Marcos","Santee","Poway","La Mesa","National City"],
  "CA::Orange": ["Anaheim","Santa Ana","Irvine","Huntington Beach","Garden Grove","Fullerton","Orange","Costa Mesa","Mission Viejo","Newport Beach","Tustin","Lake Forest"],
  "CA::Santa Clara": ["San Jose","Sunnyvale","Santa Clara","Mountain View","Palo Alto","Milpitas","Campbell","Cupertino","Los Gatos","Gilroy","Morgan Hill"],
  "CA::Alameda": ["Oakland","Fremont","Hayward","Berkeley","Livermore","Newark","Union City","Pleasanton","Dublin","San Leandro","Emeryville"],
  "CA::Sacramento": ["Sacramento","Elk Grove","Roseville","Folsom","Citrus Heights","Rancho Cordova","Elk Grove","Arden-Arcade"],
  "CA::Riverside": ["Riverside","Moreno Valley","Corona","Temecula","Murrieta","Hemet","Indio","Palm Springs","Perris","Menifee"],
  "CA::San Bernardino": ["San Bernardino","Fontana","Ontario","Rancho Cucamonga","Victorville","Rialto","Hesperia","Chino","Chino Hills","Upland"],
  "CA::Contra Costa": ["Concord","Richmond","Antioch","Walnut Creek","Pittsburg","San Ramon","Brentwood","Oakley"],
  "CA::Ventura": ["Oxnard","Thousand Oaks","Simi Valley","Ventura","Camarillo","Moorpark","Santa Paula"],
  "CA::San Mateo": ["Daly City","San Mateo","Redwood City","South San Francisco","San Bruno","Burlingame","Foster City"],
  "CA::Fresno": ["Fresno","Clovis","Sanger","Reedley","Madera"],
  "CA::Kern": ["Bakersfield","Delano","Ridgecrest","Tehachapi"],
  "CA::Solano": ["Vallejo","Fairfield","Vacaville","Suisun City","Benicia"],
  "CA::Sonoma": ["Santa Rosa","Petaluma","Rohnert Park","Windsor","Healdsburg"],
  "CA::San Joaquin": ["Stockton","Lodi","Tracy","Manteca","Turlock"],
  "CA::Stanislaus": ["Modesto","Turlock","Ceres","Riverbank","Oakdale"],
  "CA::Tulare": ["Visalia","Tulare","Porterville","Dinuba","Exeter"],
  "CA::Placer": ["Roseville","Rocklin","Lincoln","Auburn","Folsom"],
  "CA::Santa Cruz": ["Santa Cruz","Watsonville","Scotts Valley","Capitola"],
  "CA::Monterey": ["Salinas","Monterey","Seaside","Marina","Pacific Grove"],
  "CA::Marin": ["San Rafael","Novato","Mill Valley","Tiburon"],
  "CA::Shasta": ["Redding","Anderson","Shasta Lake"],
  // Colorado
  "CO::Denver": ["Denver"],
  "CO::El Paso": ["Colorado Springs","Fountain","Manitou Springs","Monument"],
  "CO::Arapahoe": ["Aurora","Centennial","Englewood","Littleton","Cherry Hills Village"],
  "CO::Jefferson": ["Lakewood","Arvada","Westminster","Wheat Ridge","Golden","Littleton"],
  "CO::Adams": ["Aurora","Westminster","Thornton","Commerce City","Brighton","Federal Heights"],
  "CO::Douglas": ["Castle Rock","Parker","Highlands Ranch","Lone Tree","Castle Pines"],
  "CO::Boulder": ["Boulder","Longmont","Louisville","Lafayette","Broomfield","Erie"],
  "CO::Larimer": ["Fort Collins","Loveland","Greeley","Windsor","Timnath"],
  "CO::Weld": ["Greeley","Evans","Windsor","Johnstown","Milliken"],
  // Connecticut
  "CT::Fairfield": ["Bridgeport","Stamford","Norwalk","Danbury","Greenwich","Westport","Trumbull"],
  "CT::Hartford": ["Hartford","New Britain","West Hartford","Bristol","Enfield","Southington"],
  "CT::New Haven": ["New Haven","Waterbury","Meriden","Milford","Hamden","West Haven"],
  "CT::New London": ["New London","Norwich","Groton","Waterford"],
  "CT::Middlesex": ["Middletown","Cromwell","Portland"],
  "CT::Litchfield": ["Torrington","Watertown","Naugatuck"],
  // Delaware
  "DE::New Castle": ["Wilmington","Newark","Dover","Middletown","Bear"],
  "DE::Kent": ["Dover","Smyrna","Milford"],
  "DE::Sussex": ["Georgetown","Rehoboth Beach","Lewes","Seaford"],
  // Florida
  "FL::Miami-Dade": ["Miami","Hialeah","Miami Gardens","Miramar","Coral Springs","Pembroke Pines","Doral","Homestead","North Miami","Coral Gables"],
  "FL::Broward": ["Fort Lauderdale","Hollywood","Pembroke Pines","Miramar","Coral Springs","Pompano Beach","Davie","Plantation","Sunrise","Weston"],
  "FL::Palm Beach": ["West Palm Beach","Boca Raton","Boynton Beach","Delray Beach","Wellington","Jupiter","Lake Worth","Palm Beach Gardens"],
  "FL::Hillsborough": ["Tampa","Brandon","Riverview","Plant City","Temple Terrace","Valrico"],
  "FL::Orange": ["Orlando","Kissimmee","Apopka","Ocoee","Winter Park","Sanford","Altamonte Springs"],
  "FL::Duval": ["Jacksonville","Jacksonville Beach","Neptune Beach","Atlantic Beach"],
  "FL::Pinellas": ["St. Petersburg","Clearwater","Largo","Dunedin","Tarpon Springs","Pinellas Park"],
  "FL::Pasco": ["New Port Richey","Wesley Chapel","Zephyrhills","Dade City","Land O' Lakes"],
  "FL::Sarasota": ["Sarasota","Venice","North Port","Englewood","Osprey"],
  "FL::Lee": ["Fort Myers","Cape Coral","Bonita Springs","Estero","Lehigh Acres"],
  "FL::Collier": ["Naples","Marco Island","Immokalee","Golden Gate"],
  "FL::Volusia": ["Daytona Beach","Deltona","Port Orange","Ormond Beach","DeLand","Edgewater"],
  "FL::Seminole": ["Sanford","Altamonte Springs","Oviedo","Casselberry","Longwood"],
  "FL::Brevard": ["Melbourne","Palm Bay","Titusville","Cocoa","Rockledge","Viera"],
  "FL::Polk": ["Lakeland","Winter Haven","Bartow","Haines City","Auburndale"],
  "FL::Osceola": ["Kissimmee","St. Cloud","Celebration","Poinciana"],
  "FL::Lake": ["Leesburg","Clermont","Eustis","Mount Dora","Tavares"],
  "FL::Manatee": ["Bradenton","Palmetto","Lakewood Ranch","Ellenton"],
  "FL::Escambia": ["Pensacola","Pensacola Beach","Ferry Pass"],
  "FL::Leon": ["Tallahassee"],
  "FL::Alachua": ["Gainesville","Newberry","Archer"],
  "FL::Bay": ["Panama City","Panama City Beach","Lynn Haven","Callaway"],
  "FL::St. Johns": ["St. Augustine","Ponte Vedra Beach","Palm Valley","Fruit Cove"],
  "FL::Marion": ["Ocala","Belleview","Dunnellon"],
  "FL::Charlotte": ["Port Charlotte","Punta Gorda","Englewood"],
  "FL::St. Lucie": ["Port St. Lucie","Fort Pierce","Stuart"],
  "FL::Indian River": ["Vero Beach","Sebastian","Fellsmere"],
  "FL::Clay": ["Orange Park","Fleming Island","Middleburg"],
  "FL::Nassau": ["Fernandina Beach","Yulee","Callahan"],
  "FL::Okaloosa": ["Fort Walton Beach","Destin","Niceville","Crestview"],
  "FL::Sumter": ["The Villages","Wildwood","Bushnell"],
  "FL::Putnam": ["Palatka","Crescent City"],
  "FL::Martin": ["Stuart","Palm City","Hobe Sound"],
  // Georgia
  "GA::Fulton": ["Atlanta","Sandy Springs","Alpharetta","Roswell","Johns Creek","Milton"],
  "GA::Gwinnett": ["Lawrenceville","Duluth","Snellville","Norcross","Buford","Lilburn","Suwanee"],
  "GA::Cobb": ["Marietta","Smyrna","Kennesaw","Acworth","Powder Springs"],
  "GA::DeKalb": ["Decatur","Tucker","Dunwoody","Stone Mountain","Chamblee"],
  "GA::Cherokee": ["Canton","Woodstock","Ball Ground","Holly Springs"],
  "GA::Forsyth": ["Cumming","Suwanee","Johns Creek"],
  "GA::Clayton": ["Jonesboro","Morrow","Forest Park","Riverdale"],
  "GA::Henry": ["McDonough","Stockbridge","Hampton","Locust Grove"],
  "GA::Muscogee": ["Columbus"],
  "GA::Richmond": ["Augusta","Martinez","Evans"],
  "GA::Hall": ["Gainesville","Oakwood","Flowery Branch"],
  "GA::Bartow": ["Cartersville","Adairsville"],
  "GA::Carroll": ["Carrollton","Villa Rica"],
  "GA::Paulding": ["Dallas","Hiram","Powder Springs"],
  "GA::Newton": ["Covington","Oxford","Porterdale"],
  "GA::Whitfield": ["Dalton","Tunnel Hill"],
  "GA::Houston": ["Warner Robins","Perry","Centerville"],
  "GA::Columbia": ["Evans","Grovetown","Harlem"],
  // Hawaii
  "HI::Honolulu": ["Honolulu","Pearl City","Kailua","Kaneohe","Mililani","Ewa Beach","Kapolei"],
  "HI::Hawaii": ["Hilo","Kailua-Kona","Waimea","Pahoa"],
  "HI::Maui": ["Kahului","Lahaina","Kihei","Wailuku","Makawao"],
  "HI::Kauai": ["Lihue","Kapaa","Princeville","Waimea"],
  // Idaho
  "ID::Ada": ["Boise","Meridian","Nampa","Caldwell","Eagle","Star","Kuna"],
  "ID::Canyon": ["Nampa","Caldwell","Middleton","Notus","Wilder"],
  "ID::Kootenai": ["Coeur d'Alene","Post Falls","Hayden","Rathdrum"],
  "ID::Bonneville": ["Idaho Falls","Ammon","Ucon"],
  "ID::Bannock": ["Pocatello","Chubbuck"],
  "ID::Twin Falls": ["Twin Falls","Kimberly","Filer"],
  // Illinois
  "IL::Cook": ["Chicago","Evanston","Skokie","Oak Park","Cicero","Berwyn","Schaumburg","Naperville","Arlington Heights","Palatine"],
  "IL::DuPage": ["Naperville","Aurora","Wheaton","Downers Grove","Lombard","Elmhurst","Bolingbrook","Lisle"],
  "IL::Lake": ["Waukegan","Elgin","Joliet","Rockford","Gurnee","Libertyville","Round Lake Beach"],
  "IL::Will": ["Joliet","Bolingbrook","Romeoville","Plainfield","Lockport","Crest Hill"],
  "IL::Kane": ["Aurora","Elgin","St. Charles","Geneva","Batavia","Carpentersville"],
  "IL::Winnebago": ["Rockford","Loves Park","Machesney Park","Belvidere"],
  "IL::Sangamon": ["Springfield","Sherman","Chatham"],
  "IL::Peoria": ["Peoria","Pekin","East Peoria","Morton"],
  "IL::Champaign": ["Champaign","Urbana","Savoy","Rantoul"],
  "IL::St. Clair": ["Belleville","O'Fallon","Collinsville","Fairview Heights"],
  // Indiana
  "IN::Marion": ["Indianapolis","Lawrence","Beech Grove","Southport"],
  "IN::Hamilton": ["Carmel","Fishers","Noblesville","Westfield","Cicero"],
  "IN::Allen": ["Fort Wayne","New Haven","Huntertown"],
  "IN::Lake": ["Gary","Hammond","Merrillville","Munster","Highland","Dyer"],
  "IN::St. Joseph": ["South Bend","Mishawaka","Granger","Osceola"],
  "IN::Tippecanoe": ["Lafayette","West Lafayette","Dayton"],
  "IN::Elkhart": ["Elkhart","Goshen","Nappanee"],
  "IN::Hendricks": ["Avon","Plainfield","Brownsburg","Danville"],
  "IN::Johnson": ["Greenwood","Franklin","Bargersville"],
  "IN::Monroe": ["Bloomington","Ellettsville"],
  // Iowa
  "IA::Polk": ["Des Moines","Ankeny","Urbandale","West Des Moines","Clive","Johnston"],
  "IA::Linn": ["Cedar Rapids","Marion","Hiawatha"],
  "IA::Scott": ["Davenport","Bettendorf","Eldridge"],
  "IA::Johnson": ["Iowa City","Coralville","North Liberty"],
  "IA::Black Hawk": ["Waterloo","Cedar Falls","Evansdale"],
  "IA::Story": ["Ames","Nevada","Gilbert"],
  "IA::Dallas": ["Waukee","Adel","Perry"],
  "IA::Woodbury": ["Sioux City","North Sioux City"],
  // Kansas
  "KS::Johnson": ["Overland Park","Olathe","Shawnee","Lenexa","Leawood","Prairie Village"],
  "KS::Sedgwick": ["Wichita","Derby","Andover","Haysville","Park City"],
  "KS::Wyandotte": ["Kansas City","Bonner Springs"],
  "KS::Shawnee": ["Topeka","Auburn","Rossville"],
  "KS::Douglas": ["Lawrence","Eudora","Baldwin City"],
  // Kentucky
  "KY::Jefferson": ["Louisville","St. Matthews","Jeffersontown","Shively","Okolona"],
  "KY::Fayette": ["Lexington","Nicholasville"],
  "KY::Boone": ["Florence","Burlington","Hebron","Union"],
  "KY::Kenton": ["Covington","Independence","Erlanger","Florence"],
  "KY::Warren": ["Bowling Green","Smiths Grove"],
  "KY::Daviess": ["Owensboro","Whitesville"],
  "KY::Madison": ["Richmond","Berea"],
  "KY::Campbell": ["Newport","Ft. Thomas","Alexandria"],
  // Louisiana
  "LA::Orleans": ["New Orleans"],
  "LA::Jefferson": ["Metairie","Kenner","Gretna","Harvey","Marrero"],
  "LA::East Baton Rouge": ["Baton Rouge","Zachary","Baker","Central"],
  "LA::Caddo": ["Shreveport","Bossier City"],
  "LA::Bossier": ["Bossier City","Haughton","Benton"],
  "LA::Lafayette": ["Lafayette","Broussard","Youngsville","Scott","Carencro"],
  "LA::Calcasieu": ["Lake Charles","Sulphur","Westlake","DeRidder"],
  "LA::St. Tammany": ["Slidell","Covington","Mandeville","Madisonville"],
  "LA::Ascension": ["Gonzales","Prairieville","Sorrento"],
  "LA::Ouachita": ["Monroe","West Monroe"],
  // Maine
  "ME::Cumberland": ["Portland","South Portland","Westbrook","Gorham","Scarborough"],
  "ME::York": ["Biddeford","Saco","Sanford","Kennebunk"],
  "ME::Penobscot": ["Bangor","Brewer","Old Town"],
  "ME::Kennebec": ["Augusta","Waterville","Gardiner"],
  "ME::Androscoggin": ["Lewiston","Auburn","Lisbon"],
  // Maryland
  "MD::Montgomery": ["Rockville","Gaithersburg","Silver Spring","Bethesda","Germantown","Potomac"],
  "MD::Prince George's": ["Bowie","College Park","Laurel","Hyattsville","Greenbelt","Oxon Hill"],
  "MD::Baltimore County": ["Towson","Dundalk","Catonsville","Pikesville","Owings Mills","Timonium"],
  "MD::Baltimore City": ["Baltimore"],
  "MD::Anne Arundel": ["Annapolis","Glen Burnie","Severn","Odenton","Pasadena"],
  "MD::Howard": ["Columbia","Ellicott City","Elkridge","Jessup"],
  "MD::Frederick": ["Frederick","Hagerstown","Gaithersburg","Urbana"],
  "MD::Harford": ["Bel Air","Aberdeen","Havre de Grace","Edgewood"],
  "MD::Charles": ["Waldorf","La Plata","White Plains"],
  // Massachusetts
  "MA::Suffolk": ["Boston","Chelsea","Revere","Winthrop"],
  "MA::Middlesex": ["Cambridge","Lowell","Somerville","Newton","Waltham","Malden","Medford","Framingham","Quincy"],
  "MA::Worcester": ["Worcester","Fitchburg","Leominster","Shrewsbury","Marlborough"],
  "MA::Essex": ["Salem","Lawrence","Haverhill","Lynn","Peabody","Beverly","Gloucester"],
  "MA::Norfolk": ["Quincy","Brockton","Brookline","Weymouth","Dedham","Needham"],
  "MA::Plymouth": ["Plymouth","Brockton","Bridgewater","Middleborough"],
  "MA::Hampden": ["Springfield","Chicopee","Holyoke","Westfield","Agawam"],
  "MA::Bristol": ["New Bedford","Fall River","Taunton","Attleboro"],
  "MA::Barnstable": ["Barnstable","Hyannis","Falmouth","Yarmouth","Dennis"],
  // Michigan
  "MI::Wayne": ["Detroit","Dearborn","Livonia","Warren","Sterling Heights","Westland","Taylor","Southgate"],
  "MI::Oakland": ["Troy","Southfield","Royal Oak","Pontiac","Auburn Hills","Farmington Hills","Novi","Rochester Hills"],
  "MI::Macomb": ["Warren","Sterling Heights","Clinton Township","Roseville","Chesterfield","St. Clair Shores"],
  "MI::Kent": ["Grand Rapids","Wyoming","Kentwood","Grandville","Walker","Rockford"],
  "MI::Washtenaw": ["Ann Arbor","Ypsilanti","Saline","Dexter"],
  "MI::Ingham": ["Lansing","East Lansing","Okemos","Mason"],
  "MI::Kalamazoo": ["Kalamazoo","Portage","Comstock"],
  "MI::Genesee": ["Flint","Burton","Grand Blanc","Flushing"],
  "MI::Ottawa": ["Holland","Zeeland","Grand Haven","Hudsonville"],
  "MI::Muskegon": ["Muskegon","Norton Shores","Muskegon Heights"],
  // Minnesota
  "MN::Hennepin": ["Minneapolis","Bloomington","Plymouth","Eden Prairie","Minnetonka","Maple Grove","Brooklyn Park"],
  "MN::Ramsey": ["St. Paul","Roseville","Maplewood","Shoreview","New Brighton"],
  "MN::Dakota": ["Burnsville","Eagan","Apple Valley","Lakeville","Inver Grove Heights"],
  "MN::Anoka": ["Blaine","Coon Rapids","Fridley","Andover","Champlin"],
  "MN::Washington": ["Woodbury","Stillwater","Cottage Grove","Oakdale"],
  "MN::Scott": ["Shakopee","Prior Lake","Savage","Savage"],
  "MN::Carver": ["Chaska","Chanhassen","Waconia","Victoria"],
  "MN::Olmsted": ["Rochester","Byron","Stewartville"],
  "MN::St. Louis": ["Duluth","Hermantown","Proctor"],
  // Mississippi
  "MS::Hinds": ["Jackson","Clinton","Byram","Raymond"],
  "MS::Harrison": ["Gulfport","Biloxi","Long Beach","D'Iberville"],
  "MS::DeSoto": ["Southaven","Horn Lake","Olive Branch","Hernando"],
  "MS::Rankin": ["Brandon","Flowood","Pearl","Richland"],
  "MS::Madison": ["Madison","Ridgeland","Canton","Gluckstadt"],
  "MS::Jackson": ["Pascagoula","Gautier","Ocean Springs","Moss Point"],
  "MS::Lamar": ["Hattiesburg","Purvis","Sumrall"],
  "MS::Forrest": ["Hattiesburg","Petal"],
  // Missouri
  "MO::Jackson": ["Kansas City","Independence","Lee's Summit","Blue Springs","Raytown"],
  "MO::St. Louis County": ["St. Louis","Chesterfield","Florissant","Ballwin","Kirkwood","Clayton","Creve Coeur"],
  "MO::St. Louis City": ["St. Louis"],
  "MO::Greene": ["Springfield","Republic","Ozark","Nixa"],
  "MO::Boone": ["Columbia","Ashland","Centralia"],
  "MO::Clay": ["Liberty","Kearney","Gladstone","Excelsior Springs"],
  "MO::St. Charles": ["St. Charles","O'Fallon","St. Peters","Wentzville","Lake Saint Louis"],
  "MO::Jefferson": ["Arnold","Festus","Crystal City","Hillsboro"],
  "MO::Platte": ["Kansas City","Platte City","Parkville","Riverside"],
  "MO::Buchanan": ["St. Joseph","Savannah"],
  "MO::Cape Girardeau": ["Cape Girardeau","Jackson"],
  // Montana
  "MT::Yellowstone": ["Billings","Laurel","Lockwood"],
  "MT::Cascade": ["Great Falls","Black Eagle"],
  "MT::Missoula": ["Missoula","Lolo"],
  "MT::Gallatin": ["Bozeman","Belgrade","Manhattan"],
  "MT::Flathead": ["Kalispell","Whitefish","Columbia Falls"],
  "MT::Lewis and Clark": ["Helena","East Helena"],
  // Nebraska
  "NE::Douglas": ["Omaha","Bellevue","Ralston","Papillion"],
  "NE::Lancaster": ["Lincoln","Waverly","Hickman"],
  "NE::Sarpy": ["Papillion","Bellevue","La Vista","Gretna"],
  // Nevada
  "NV::Clark": ["Las Vegas","Henderson","North Las Vegas","Boulder City","Mesquite","Enterprise","Summerlin"],
  "NV::Washoe": ["Reno","Sparks","Sun Valley","Fernley"],
  "NV::Elko": ["Elko","Spring Creek"],
  "NV::Lyon": ["Fernley","Yerington","Dayton"],
  // New Hampshire
  "NH::Hillsborough": ["Manchester","Nashua","Merrimack","Bedford","Milford"],
  "NH::Rockingham": ["Portsmouth","Salem","Derry","Londonderry","Exeter"],
  "NH::Merrimack": ["Concord","Bow","Hooksett","Pembroke"],
  "NH::Strafford": ["Dover","Rochester","Somersworth","Durham"],
  // New Jersey
  "NJ::Bergen": ["Hackensack","Paramus","Fort Lee","Englewood","Teaneck","Ridgewood"],
  "NJ::Essex": ["Newark","East Orange","Irvington","Montclair","Bloomfield","West Orange"],
  "NJ::Hudson": ["Jersey City","Bayonne","Hoboken","Union City","West New York","Secaucus"],
  "NJ::Middlesex": ["New Brunswick","Edison","Woodbridge","Piscataway","Old Bridge","Sayreville"],
  "NJ::Monmouth": ["Freehold","Asbury Park","Long Branch","Red Bank","Howell","Toms River"],
  "NJ::Ocean": ["Toms River","Brick","Lakewood","Barnegat","Jackson"],
  "NJ::Union": ["Elizabeth","Union","Linden","Plainfield","Westfield","Rahway"],
  "NJ::Morris": ["Morristown","Parsippany","Rockaway","Dover","Denville"],
  "NJ::Passaic": ["Paterson","Clifton","Passaic","Wayne","Totowa"],
  "NJ::Camden": ["Camden","Cherry Hill","Gloucester City","Voorhees","Lindenwold"],
  "NJ::Burlington": ["Burlington","Mount Holly","Evesham","Moorestown","Medford"],
  "NJ::Mercer": ["Trenton","Princeton","Hamilton","Ewing","Lawrence"],
  "NJ::Somerset": ["Bridgewater","Somerville","Franklin","Bound Brook"],
  "NJ::Atlantic": ["Atlantic City","Egg Harbor","Galloway","Hammonton"],
  // New Mexico
  "NM::Bernalillo": ["Albuquerque","Rio Rancho","South Valley"],
  "NM::Santa Fe": ["Santa Fe","Española","Pojoaque"],
  "NM::Doña Ana": ["Las Cruces","Sunland Park","Mesilla"],
  "NM::Sandoval": ["Rio Rancho","Bernalillo","Corrales"],
  "NM::Chaves": ["Roswell","Dexter"],
  "NM::Eddy": ["Carlsbad","Artesia"],
  "NM::Lea": ["Hobbs","Lovington","Eunice"],
  // New York
  "NY::New York": ["Manhattan"],
  "NY::Kings": ["Brooklyn"],
  "NY::Queens": ["Queens","Flushing","Jamaica","Astoria","Long Island City","Bayside","Forest Hills"],
  "NY::Bronx": ["Bronx"],
  "NY::Richmond": ["Staten Island"],
  "NY::Nassau": ["Hempstead","Levittown","Valley Stream","Garden City","Long Beach","Freeport","Hicksville"],
  "NY::Suffolk": ["Babylon","Brookhaven","Huntington","Islip","Smithtown","Riverhead"],
  "NY::Westchester": ["Yonkers","New Rochelle","Mount Vernon","White Plains","Peekskill","Ossining"],
  "NY::Erie": ["Buffalo","Cheektowaga","Amherst","Tonawanda","Lackawanna","West Seneca"],
  "NY::Monroe": ["Rochester","Irondequoit","Greece","Brighton","Gates","Henrietta"],
  "NY::Onondaga": ["Syracuse","Geddes","Salina","Manlius","Dewitt"],
  "NY::Albany": ["Albany","Colonie","Guilderland","Bethlehem","Cohoes"],
  "NY::Dutchess": ["Poughkeepsie","Fishkill","Wappingers Falls","Beacon"],
  "NY::Orange": ["Middletown","Newburgh","Port Jervis","Monroe"],
  "NY::Rockland": ["New City","Spring Valley","Nanuet","Suffern"],
  "NY::Saratoga": ["Saratoga Springs","Clifton Park","Malta","Ballston Spa"],
  "NY::Ulster": ["Kingston","Woodstock","New Paltz","Saugerties"],
  "NY::Broome": ["Binghamton","Vestal","Johnson City","Endicott"],
  "NY::Niagara": ["Niagara Falls","Lockport","North Tonawanda"],
  // North Carolina
  "NC::Mecklenburg": ["Charlotte","Huntersville","Concord","Kannapolis","Matthews","Mint Hill"],
  "NC::Wake": ["Raleigh","Cary","Apex","Morrisville","Durham","Garner","Holly Springs","Fuquay-Varina"],
  "NC::Guilford": ["Greensboro","High Point","Jamestown"],
  "NC::Forsyth": ["Winston-Salem","Kernersville","Lewisville"],
  "NC::Durham": ["Durham","Research Triangle Park"],
  "NC::Buncombe": ["Asheville","Weaverville","Woodfin"],
  "NC::Cumberland": ["Fayetteville","Hope Mills","Spring Lake"],
  "NC::New Hanover": ["Wilmington","Wrightsville Beach","Carolina Beach"],
  "NC::Cabarrus": ["Concord","Kannapolis","Harrisburg"],
  "NC::Union": ["Monroe","Waxhaw","Indian Trail","Stallings"],
  "NC::Iredell": ["Statesville","Mooresville","Troutman"],
  "NC::Johnston": ["Smithfield","Clayton","Selma"],
  "NC::Gaston": ["Gastonia","Belmont","Mount Holly","Cramerton"],
  "NC::Catawba": ["Hickory","Conover","Newton"],
  "NC::Henderson": ["Hendersonville","Flat Rock","Mills River"],
  "NC::Alamance": ["Burlington","Graham","Mebane"],
  "NC::Randolph": ["Asheboro","Archdale","Trinity"],
  "NC::Rowan": ["Salisbury","Spencer","China Grove"],
  "NC::Pitt": ["Greenville","Winterville","Ayden"],
  "NC::Onslow": ["Jacksonville","Richlands","Swansboro"],
  // North Dakota
  "ND::Cass": ["Fargo","West Fargo","Moorhead"],
  "ND::Burleigh": ["Bismarck","Lincoln"],
  "ND::Grand Forks": ["Grand Forks","East Grand Forks"],
  "ND::Ward": ["Minot","Burlington"],
  // Ohio
  "OH::Cuyahoga": ["Cleveland","Parma","Lakewood","Euclid","Strongsville","Westlake","Mentor","Solon"],
  "OH::Franklin": ["Columbus","Dublin","Westerville","Grove City","Hilliard","Gahanna","Reynoldsburg"],
  "OH::Hamilton": ["Cincinnati","Norwood","Blue Ash","Mason","Fairfield","Forest Park"],
  "OH::Summit": ["Akron","Cuyahoga Falls","Stow","Barberton","Tallmadge","Hudson"],
  "OH::Montgomery": ["Dayton","Kettering","Huber Heights","Beavercreek","Centerville","Miamisburg"],
  "OH::Lucas": ["Toledo","Sylvania","Maumee","Oregon","Perrysburg"],
  "OH::Stark": ["Canton","Massillon","Alliance","North Canton"],
  "OH::Mahoning": ["Youngstown","Boardman","Austintown","Canfield"],
  "OH::Butler": ["Hamilton","Middletown","Fairfield","Oxford","Monroe"],
  "OH::Warren": ["Mason","Lebanon","Franklin","Springboro"],
  "OH::Delaware": ["Delaware","Powell","Westerville","Dublin"],
  "OH::Licking": ["Newark","Heath","Granville","Pataskala"],
  "OH::Lorain": ["Lorain","Elyria","Avon","Avon Lake","Amherst"],
  "OH::Lake": ["Mentor","Willoughby","Painesville","Eastlake","Wickliffe"],
  "OH::Portage": ["Kent","Ravenna","Aurora","Streetsboro"],
  "OH::Trumbull": ["Warren","Niles","Cortland","Hubbard"],
  "OH::Medina": ["Medina","Brunswick","Wadsworth","Strongsville"],
  "OH::Wood": ["Perrysburg","Bowling Green","Maumee"],
  "OH::Greene": ["Beavercreek","Fairborn","Xenia","Kettering"],
  "OH::Clark": ["Springfield","Enon","New Carlisle"],
  "OH::Clermont": ["Milford","Batavia","Loveland","Amelia"],
  // Oklahoma
  "OK::Oklahoma": ["Oklahoma City","Edmond","Moore","Midwest City","Del City","Yukon"],
  "OK::Tulsa": ["Tulsa","Broken Arrow","Owasso","Jenks","Bixby","Sand Springs"],
  "OK::Cleveland": ["Norman","Moore","Noble"],
  "OK::Canadian": ["Yukon","Mustang","El Reno","Weatherford"],
  "OK::Comanche": ["Lawton","Duncan"],
  "OK::Muskogee": ["Muskogee","Fort Gibson"],
  "OK::Creek": ["Sapulpa","Bristow","Drumright"],
  // Oregon
  "OR::Multnomah": ["Portland","Gresham","Troutdale","Fairview"],
  "OR::Washington": ["Beaverton","Hillsboro","Tigard","Tualatin","Sherwood","Forest Grove"],
  "OR::Clackamas": ["Oregon City","Lake Oswego","Milwaukie","Gladstone","West Linn"],
  "OR::Lane": ["Eugene","Springfield","Cottage Grove","Florence"],
  "OR::Marion": ["Salem","Keizer","Woodburn","Silverton"],
  "OR::Deschutes": ["Bend","Redmond","Sisters","La Pine"],
  "OR::Jackson": ["Medford","Ashland","Grants Pass","Central Point"],
  "OR::Linn": ["Albany","Corvallis","Lebanon","Sweet Home"],
  // Pennsylvania
  "PA::Philadelphia": ["Philadelphia"],
  "PA::Allegheny": ["Pittsburgh","McKeesport","Bethel Park","Mt. Lebanon","Monroeville","Penn Hills"],
  "PA::Montgomery": ["Norristown","King of Prussia","Lansdale","Abington","Horsham","Cheltenham"],
  "PA::Bucks": ["Levittown","Bristol","Doylestown","Newtown","Warminster","Bensalem"],
  "PA::Delaware": ["Chester","Upper Darby","Media","Springfield","Haverford"],
  "PA::Chester": ["West Chester","Coatesville","Phoenixville","Downingtown","Malvern"],
  "PA::Lancaster": ["Lancaster","Manheim","Ephrata","Lititz","Columbia"],
  "PA::York": ["York","Hanover","Spring Grove","Red Lion"],
  "PA::Berks": ["Reading","Wyomissing","Kutztown","Birdsboro"],
  "PA::Lehigh": ["Allentown","Emmaus","Whitehall","Bethlehem","Macungie"],
  "PA::Northampton": ["Bethlehem","Easton","Nazareth","Wilson"],
  "PA::Luzerne": ["Wilkes-Barre","Hazleton","Pittston","Kingston","Nanticoke"],
  "PA::Erie": ["Erie","Millcreek","Harborcreek"],
  "PA::Cumberland": ["Mechanicsburg","Carlisle","Camp Hill","New Cumberland"],
  "PA::Dauphin": ["Harrisburg","Hershey","Middletown","Steelton"],
  "PA::Westmoreland": ["Greensburg","Murrysville","Jeannette","Latrobe"],
  "PA::Monroe": ["Stroudsburg","East Stroudsburg","Pocono Summit"],
  "PA::Lebanon": ["Lebanon","Palmyra","Annville"],
  // Rhode Island
  "RI::Providence": ["Providence","Cranston","Pawtucket","Woonsocket","North Providence","Johnston"],
  "RI::Kent": ["Warwick","Coventry","West Warwick","East Greenwich"],
  "RI::Washington": ["South Kingstown","Westerly","Narragansett","North Kingstown"],
  "RI::Newport": ["Newport","Middletown","Portsmouth","Tiverton"],
  "RI::Bristol": ["Bristol","Warren","Barrington"],
  // South Carolina
  "SC::Greenville": ["Greenville","Simpsonville","Mauldin","Greer","Taylors"],
  "SC::Richland": ["Columbia","Forest Acres","Irmo","Cayce"],
  "SC::Charleston": ["Charleston","North Charleston","Mount Pleasant","Summerville","Goose Creek"],
  "SC::Horry": ["Myrtle Beach","Conway","Socastee","Surfside Beach"],
  "SC::Spartanburg": ["Spartanburg","Duncan","Boiling Springs","Greer","Inman"],
  "SC::York": ["Rock Hill","Fort Mill","Clover","Tega Cay"],
  "SC::Lexington": ["Lexington","Irmo","Cayce","West Columbia","Chapin"],
  "SC::Anderson": ["Anderson","Clemson","Pendleton","Powdersville"],
  "SC::Berkeley": ["Goose Creek","Moncks Corner","Hanahan","Summerville"],
  // South Dakota
  "SD::Minnehaha": ["Sioux Falls","Brandon","Harrisburg","Tea"],
  "SD::Pennington": ["Rapid City","Box Elder","Summerset"],
  // Tennessee
  "TN::Shelby": ["Memphis","Germantown","Bartlett","Collierville","Cordova","Millington"],
  "TN::Davidson": ["Nashville","Brentwood","Antioch","Hermitage","Madison"],
  "TN::Knox": ["Knoxville","Farragut","Powell","Halls","Corryton"],
  "TN::Hamilton": ["Chattanooga","East Ridge","Hixson","Ooltewah","Soddy-Daisy"],
  "TN::Rutherford": ["Murfreesboro","Smyrna","La Vergne","Eagleville"],
  "TN::Williamson": ["Franklin","Brentwood","Spring Hill","Nolensville","Fairview"],
  "TN::Montgomery": ["Clarksville","Oak Grove"],
  "TN::Sullivan": ["Kingsport","Bristol","Blountville"],
  "TN::Washington": ["Johnson City","Jonesborough"],
  "TN::Blount": ["Maryville","Alcoa","Friendsville"],
  "TN::Bradley": ["Cleveland","Charleston"],
  "TN::Maury": ["Columbia","Spring Hill","Mount Pleasant"],
  "TN::Madison": ["Jackson","Humboldt"],
  "TN::Wilson": ["Lebanon","Mt. Juliet","Watertown"],
  "TN::Sumner": ["Hendersonville","Gallatin","Portland","Goodlettsville"],
  // Texas
  "TX::Harris": ["Houston","Pasadena","Pearland","Baytown","Sugar Land","Missouri City","Katy","Humble","Conroe"],
  "TX::Dallas": ["Dallas","Irving","Garland","Mesquite","Richardson","Carrollton","Grand Prairie","Rowlett","Duncanville"],
  "TX::Tarrant": ["Fort Worth","Arlington","Irving","Grand Prairie","Mansfield","Euless","Bedford","Hurst","Keller","Southlake"],
  "TX::Bexar": ["San Antonio","Converse","Universal City","Schertz","Live Oak","Helotes","Leon Valley"],
  "TX::Travis": ["Austin","Cedar Park","Round Rock","Pflugerville","Leander","Manor","Buda"],
  "TX::Collin": ["Plano","McKinney","Frisco","Allen","Wylie","Garland","Murphy","Prosper"],
  "TX::Denton": ["Denton","Lewisville","Frisco","Flower Mound","Carrollton","The Colony","Little Elm","Corinth"],
  "TX::Williamson": ["Round Rock","Georgetown","Cedar Park","Leander","Taylor","Hutto","Pflugerville"],
  "TX::El Paso": ["El Paso","Socorro","Horizon City","Anthony"],
  "TX::Lubbock": ["Lubbock","Wolfforth","Slaton"],
  "TX::McLennan": ["Waco","Woodway","Hewitt","Bellmead","Lorena"],
  "TX::Nueces": ["Corpus Christi","Portland","Robstown"],
  "TX::Webb": ["Laredo","Rio Bravo"],
  "TX::Hidalgo": ["McAllen","Edinburg","Mission","Pharr","Weslaco","Harlingen"],
  "TX::Cameron": ["Brownsville","Harlingen","San Benito","Weslaco"],
  "TX::Fort Bend": ["Sugar Land","Missouri City","Pearland","Stafford","Richmond","Rosenberg"],
  "TX::Montgomery": ["Conroe","The Woodlands","Spring","Humble","Magnolia","Shenandoah"],
  "TX::Brazoria": ["Pearland","Alvin","Lake Jackson","Angleton","Friendswood"],
  "TX::Galveston": ["Galveston","Texas City","League City","Friendswood","La Marque"],
  "TX::Smith": ["Tyler","Lindale","Whitehouse"],
  "TX::Brazos": ["Bryan","College Station","Hearne"],
  "TX::Hays": ["San Marcos","Kyle","Buda","Wimberley"],
  "TX::Comal": ["New Braunfels","Canyon Lake","Bulverde"],
  "TX::Bell": ["Killeen","Temple","Belton","Harker Heights","Waco"],
  "TX::Jefferson": ["Beaumont","Port Arthur","Orange","Nederland"],
  "TX::Taylor": ["Abilene","Wylie","Tye"],
  "TX::Potter": ["Amarillo"],
  "TX::Randall": ["Amarillo","Canyon"],
  "TX::Parker": ["Weatherford","Aledo","Springtown"],
  "TX::Johnson": ["Burleson","Cleburne","Joshua","Crowley"],
  // Utah
  "UT::Salt Lake": ["Salt Lake City","West Valley City","Sandy","West Jordan","Murray","Taylorsville","Millcreek","Cottonwood Heights"],
  "UT::Utah": ["Provo","Orem","Lehi","American Fork","Springville","Pleasant Grove","Saratoga Springs"],
  "UT::Davis": ["Layton","Bountiful","Clearfield","Kaysville","Syracuse","Clinton"],
  "UT::Weber": ["Ogden","Roy","Layton","Riverdale","Washington Terrace"],
  "UT::Washington": ["St. George","Washington","Ivins","Hurricane","Santa Clara"],
  "UT::Cache": ["Logan","North Logan","Providence","Smithfield"],
  // Vermont
  "VT::Chittenden": ["Burlington","South Burlington","Williston","Colchester","Essex"],
  "VT::Rutland": ["Rutland","Castleton","Poultney"],
  "VT::Washington": ["Montpelier","Barre","Northfield"],
  "VT::Windham": ["Brattleboro","Bellows Falls","Wilmington"],
  "VT::Windsor": ["White River Junction","Springfield","Windsor"],
  "VT::Addison": ["Middlebury","Vergennes","Bristol"],
  // Virginia
  "VA::Fairfax": ["Fairfax","Reston","Herndon","McLean","Vienna","Annandale","Springfield","Burke"],
  "VA::Virginia Beach City": ["Virginia Beach"],
  "VA::Chesterfield": ["Chester","Midlothian","Bon Air","Colonial Heights"],
  "VA::Prince William": ["Manassas","Woodbridge","Dale City","Dumfries","Gainesville"],
  "VA::Loudoun": ["Leesburg","Ashburn","Sterling","Lansdowne","Purcellville"],
  "VA::Henrico": ["Richmond","Henrico","Short Pump","Glen Allen"],
  "VA::Richmond City": ["Richmond"],
  "VA::Arlington": ["Arlington","Rosslyn","Ballston","Clarendon"],
  "VA::Alexandria City": ["Alexandria"],
  "VA::Roanoke": ["Roanoke","Salem","Vinton"],
  // Washington
  "WA::King": ["Seattle","Bellevue","Renton","Kent","Kirkland","Redmond","Sammamish","Auburn","Federal Way","Shoreline","Burien"],
  "WA::Pierce": ["Tacoma","Lakewood","Puyallup","Federal Way","Bonney Lake","Sumner"],
  "WA::Snohomish": ["Everett","Marysville","Lynnwood","Edmonds","Mukilteo","Bothell","Mill Creek"],
  "WA::Spokane": ["Spokane","Spokane Valley","Cheney","Liberty Lake"],
  "WA::Clark": ["Vancouver","Camas","Battle Ground","Washougal","Ridgefield"],
  "WA::Thurston": ["Olympia","Lacey","Tumwater","Yelm"],
  "WA::Kitsap": ["Bremerton","Poulsbo","Port Orchard","Bainbridge Island"],
  "WA::Whatcom": ["Bellingham","Ferndale","Lynden","Blaine"],
  "WA::Yakima": ["Yakima","Selah","Union Gap","Sunnyside"],
  // West Virginia
  "WV::Kanawha": ["Charleston","South Charleston","St. Albans","Dunbar"],
  "WV::Cabell": ["Huntington","Barboursville","Milton"],
  "WV::Berkeley": ["Martinsburg","Hedgesville","Inwood"],
  "WV::Monongalia": ["Morgantown","Westover","Star City"],
  "WV::Wood": ["Parkersburg","Vienna","Williamstown"],
  // Wisconsin
  "WI::Milwaukee": ["Milwaukee","Wauwatosa","West Allis","Greenfield","Greendale","Oak Creek","Franklin"],
  "WI::Dane": ["Madison","Fitchburg","Sun Prairie","Middleton","Verona","Monona"],
  "WI::Waukesha": ["Waukesha","Brookfield","Pewaukee","Oconomowoc","New Berlin","Muskego"],
  "WI::Brown": ["Green Bay","De Pere","Ashwaubenon","Howard","Allouez"],
  "WI::Racine": ["Racine","Kenosha","Mount Pleasant","Caledonia"],
  "WI::Outagamie": ["Appleton","Neenah","Menasha","Kaukauna"],
  "WI::Winnebago": ["Oshkosh","Neenah","Menasha","Omro"],
  "WI::Marathon": ["Wausau","Weston","Rib Mountain","Rothschild"],
  "WI::La Crosse": ["La Crosse","Onalaska","Holmen"],
  "WI::Sheboygan": ["Sheboygan","Sheboygan Falls","Plymouth"],
  "WI::Kenosha": ["Kenosha","Pleasant Prairie","Somers"],
  "WI::Rock": ["Janesville","Beloit","Milton"],
  // Wyoming
  "WY::Laramie": ["Cheyenne","Burns","Pine Bluffs"],
  "WY::Natrona": ["Casper","Mills","Evansville"],
  "WY::Campbell": ["Gillette","Wright"],
  "WY::Sweetwater": ["Rock Springs","Green River"],
  // DC
  "DC::Washington": ["Washington"],
};

// ─── Helper functions ─────────────────────────────────────────────────────────

export function getCountiesForState(stateAbbr: string): string[] {
  return COUNTIES_BY_STATE[stateAbbr] ?? [];
}

export function getCitiesForCounty(stateAbbr: string, county: string): string[] {
  return CITIES_BY_COUNTY[`${stateAbbr}::${county}`] ?? [];
}

export function getIndustriesForCategory(category: IndustryCategory | string): string[] {
  return INDUSTRIES_BY_CATEGORY[category as IndustryCategory] ?? [];
}

/** Build a human-readable location string from structured fields */
export function formatLocation(
  city?: string | null,
  county?: string | null,
  state?: string | null
): string {
  const parts: string[] = [];
  if (city) parts.push(city);
  else if (county) parts.push(county);
  if (state) parts.push(state);
  return parts.join(", ");
}
